name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # har din raat 12 baje run hoga
  workflow_dispatch: # manually bhi run kar sakte ho

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: harsh5ingh
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generated snake animation"
          add: "dist/*"
